name = "OptimizationBase"
uuid = "bca83a33-5cc9-4baa-983d-23429ab6bcbb"
authors = ["Vaibhav Dixit <vaibhavyashdixit@gmail.com> and contributors"]
version = "1.3.3"

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Manifolds = "1cead3c2-87b3-11e9-0ccd-23c62b72b94e"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SymbolicAnalysis = "4297ee4d-0239-47d8-ba5d-195ecdf594fe"
SymbolicIndexingInterface = "2efcf032-c050-4f8e-a9bb-153293bab1f5"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
SparseConnectivityTracer = "9f842d2f-2579-4b1d-911e-f412cf18a3f5"

[weakdeps]
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[extensions]
OptimizationDIExt = "DifferentiationInterface"
OptimizationMTKExt = "ModelingToolkit"
OptimizationZygoteExt = ["Zygote", "DifferentiationInterface"]

[compat]
ADTypes = "1.3"
ArrayInterface = "7.6"
DocStringExtensions = "0.9"
LinearAlgebra = "1.9, 1.10"
ModelingToolkit = "9"
Reexport = "1.2"
Requires = "1"
SciMLBase = "2"
SparseDiffTools = "2.14"
SymbolicAnalysis = "0.1, 0.2"
SymbolicIndexingInterface = "0.3"
Symbolics = "5.12"
Tracker = "0.2.29"
Zygote = "0.6.67"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
